parameters:
  - name: environmentName
    type: string
  - name: azureSubscription
    type: string
  - name: adoEnvironment
    type: string
 
jobs:
  - deployment: Deploy_${{ parameters.environmentName}}
    displayName: 'Deploy to ${{ parameters.environmentName }}'
    environment: ${{ parameters.adoEnvironment }}
    strategy:
     runOnce:
       deploy:
        steps:  
        # download none : to avoid any auto-downloads of artifacts 
        - download: none
        # Task to download zipped Artifact from the Artifact location
        - task: DownloadBuildArtifacts@1
          displayName: 'Download Func Artifact'
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: '$(Build.DefinitionName)'
            itemPattern: '$(Build.DefinitionName)/**'
            downloadPath: '$(Build.ArtifactStagingDirectory)'

        # deploy to function app per below parameters 
        - task: AzureFunctionApp@1
          displayName: 'Azure Function Deploy'
          inputs:
            azureSubscription: ${{ parameters.azureSubscription }}
            appType: 'functionAppLinux'
            appName: '$(clientPyFuncAppName)'
            package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
            #deployToSlotOrASE: true
            resourceGroupName: $(resourceGroupName)